CREATE TABLE account (
    id BIGINT(20) AUTO_INCREMENT NOT NULL UNIQUE  PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    address1 VARCHAR(255),
    address2 VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    postal_code VARCHAR(255),
    phone_number VARCHAR(255)
);

CREATE TABLE product (
id BIGINT(20) AUTO_INCREMENT NOT NULL UNIQUE  PRIMARY KEY,
slug VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
description VARCHAR(1000),
price INT(11) NOT NULL,
quantity INT(11) NOT NULL
);